// Vietnamese language constants for Admin App
export const VI_ADMIN = {
  // Common
  common: {
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    success: 'Thành công',
    cancel: 'Hủy',
    save: 'Lưu',
    delete: 'Xóa',
    edit: 'Sửa',
    add: 'Thêm',
    search: 'Tìm kiếm',
    filter: 'Lọc',
    actions: 'Hành động',
    refresh: 'Làm mới',
    export: 'Xuất',
    import: 'Nhập',
    upload: 'Tải lên',
    download: 'Tải xuống',
    view: 'Xem',
    close: 'Đóng',
    confirm: 'Xác nhận',
    submit: 'Gửi',
    reset: 'Đặt lại',
  },

  // Auth
  auth: {
    signIn: 'Đăng nhập',
    signOut: 'Đăng xuất',
    email: 'Email',
    password: 'Mật khẩu',
    rememberMe: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    signInToAccount: 'Đăng nhập vào tài khoản quản trị',
    invalidCredentials: 'Email hoặc mật khẩu không đúng',
  },

  // Navigation
  nav: {
    dashboard: 'Tổng Quan',
    products: 'Sản phẩm',
    categories: 'Danh mục',
    brands: 'Thương hiệu',
    orders: 'Đơn hàng',
    customers: 'Khách hàng',
    promotions: 'Khuyến mãi',
    banners: 'Banner',
    settings: 'Cài đặt',
    reports: 'Báo cáo',
  },

  // Dashboard
  dashboard: {
    title: 'Tổng Quan',
    welcome: 'Chào mừng quay trở lại',
    statistics: 'Thống kê',
    totalRevenue: 'Tổng doanh thu',
    totalOrders: 'Tổng đơn hàng',
    totalProducts: 'Tổng sản phẩm',
    totalCustomers: 'Tổng khách hàng',
    recentOrders: 'Đơn hàng gần đây',
    topProducts: 'Sản phẩm bán chạy',
    revenueChart: 'Biểu đồ doanh thu',
  },

  // Products
  products: {
    title: 'Quản lý sản phẩm',
    addProduct: 'Thêm sản phẩm',
    editProduct: 'Sửa sản phẩm',
    deleteProduct: 'Xóa sản phẩm',
    productName: 'Tên sản phẩm',
    productCode: 'Mã sản phẩm',
    description: 'Mô tả',
    price: 'Giá',
    originalPrice: 'Giá gốc',
    discount: 'Giảm giá',
    stock: 'Tồn kho',
    category: 'Danh mục',
    brand: 'Thương hiệu',
    image: 'Hình ảnh',
    images: 'Hình ảnh',
    status: 'Trạng thái',
    active: 'Hoạt động',
    inactive: 'Không hoạt động',
    inStock: 'Còn hàng',
    outOfStock: 'Hết hàng',
    featured: 'Nổi bật',
    searchPlaceholder: 'Tìm theo tên, mã hoặc mô tả',
    noProducts: 'Chưa có sản phẩm nào',
    deleteConfirm: 'Bạn có chắc muốn xóa sản phẩm này?',
    uploadImage: 'Tải lên hình ảnh',
    uploadSuccess: 'Tải lên thành công',
    uploadFailed: 'Tải lên thất bại',
    selectCategory: 'Chọn danh mục',
    selectBrand: 'Chọn thương hiệu',
  },

  // Categories
  categories: {
    title: 'Quản lý danh mục',
    addCategory: 'Thêm danh mục',
    editCategory: 'Sửa danh mục',
    deleteCategory: 'Xóa danh mục',
    categoryName: 'Tên danh mục',
    description: 'Mô tả',
    noCategories: 'Chưa có danh mục nào',
    deleteConfirm: 'Bạn có chắc muốn xóa danh mục này?',
    productCount: 'Số sản phẩm',
  },

  // Brands
  brands: {
    title: 'Quản lý thương hiệu',
    addBrand: 'Thêm thương hiệu',
    editBrand: 'Sửa thương hiệu',
    deleteBrand: 'Xóa thương hiệu',
    brandName: 'Tên thương hiệu',
    description: 'Mô tả',
    noBrands: 'Chưa có thương hiệu nào',
    deleteConfirm: 'Bạn có chắc muốn xóa thương hiệu này?',
    productCount: 'Số sản phẩm',
  },

  // Orders
  orders: {
    title: 'Quản lý đơn hàng',
    orderNumber: 'Mã đơn hàng',
    customer: 'Khách hàng',
    date: 'Ngày đặt',
    status: 'Trạng thái',
    total: 'Tổng tiền',
    actions: 'Hành động',
    viewDetails: 'Xem chi tiết',
    updateStatus: 'Cập nhật trạng thái',
    pending: 'Chờ xử lý',
    processing: 'Đang xử lý',
    shipped: 'Đã gửi hàng',
    delivered: 'Đã giao hàng',
    cancelled: 'Đã hủy',
    paid: 'Đã thanh toán',
    unpaid: 'Chưa thanh toán',
    noOrders: 'Chưa có đơn hàng nào',
    orderDetails: 'Chi tiết đơn hàng',
    orderItems: 'Sản phẩm',
    shippingAddress: 'Địa chỉ giao hàng',
    paymentMethod: 'Phương thức thanh toán',
  },

  // Customers
  customers: {
    title: 'Quản lý khách hàng',
    customerName: 'Tên khách hàng',
    email: 'Email',
    phone: 'Số điện thoại',
    address: 'Địa chỉ',
    totalOrders: 'Tổng đơn hàng',
    totalSpent: 'Tổng chi tiêu',
    joinDate: 'Ngày tham gia',
    status: 'Trạng thái',
    active: 'Hoạt động',
    inactive: 'Không hoạt động',
    noCustomers: 'Chưa có khách hàng nào',
  },

  // Promotions
  promotions: {
    title: 'Quản lý khuyến mãi',
    addPromotion: 'Thêm khuyến mãi',
    editPromotion: 'Sửa khuyến mãi',
    deletePromotion: 'Xóa khuyến mãi',
    promotionName: 'Tên khuyến mãi',
    code: 'Mã khuyến mãi',
    discount: 'Giảm giá',
    discountType: 'Loại giảm giá',
    percentage: 'Phần trăm',
    fixed: 'Số tiền cố định',
    startDate: 'Ngày bắt đầu',
    endDate: 'Ngày kết thúc',
    status: 'Trạng thái',
    active: 'Đang hoạt động',
    inactive: 'Không hoạt động',
    expired: 'Đã hết hạn',
    noPromotions: 'Chưa có khuyến mãi nào',
    deleteConfirm: 'Bạn có chắc muốn xóa khuyến mãi này?',
  },

  // Banners
  banners: {
    title: 'Quản lý Banner Trang Chủ',
    addBanner: 'Thêm banner',
    editBanner: 'Sửa banner',
    deleteBanner: 'Xóa banner',
    bannerImage: 'Hình ảnh banner',
    title: 'Tiêu đề',
    subtitle: 'Mô tả ngắn',
    linkUrl: 'Đường dẫn (URL)',
    displayOrder: 'Thứ tự hiển thị',
    active: 'Kích hoạt',
    emptyMessage: 'Chưa có banner nào. Hãy tạo banner đầu tiên!',
    deleteConfirm: 'Bạn có chắc muốn xóa banner này?',
  },

  // Table
  table: {
    id: 'ID',
    name: 'Tên',
    description: 'Mô tả',
    actions: 'Hành động',
    noData: 'Không có dữ liệu',
    showing: 'Hiển thị',
    of: 'của',
    entries: 'mục',
    previous: 'Trước',
    next: 'Sau',
    page: 'Trang',
  },

  // Messages
  messages: {
    saveSuccess: 'Lưu thành công',
    saveFailed: 'Lưu thất bại',
    deleteSuccess: 'Xóa thành công',
    deleteFailed: 'Xóa thất bại',
    updateSuccess: 'Cập nhật thành công',
    updateFailed: 'Cập nhật thất bại',
    uploadSuccess: 'Tải lên thành công',
    uploadFailed: 'Tải lên thất bại',
    confirmDelete: 'Bạn có chắc muốn xóa?',
    confirmAction: 'Bạn có chắc muốn thực hiện hành động này?',
    requiredField: 'Trường này là bắt buộc',
    invalidEmail: 'Email không hợp lệ',
    invalidPhone: 'Số điện thoại không hợp lệ',
    invalidUrl: 'URL không hợp lệ',
    invalidNumber: 'Số không hợp lệ',
    invalidDate: 'Ngày không hợp lệ',
    minLength: 'Tối thiểu {min} ký tự',
    maxLength: 'Tối đa {max} ký tự',
    minValue: 'Giá trị tối thiểu là {min}',
    maxValue: 'Giá trị tối đa là {max}',
  },

  // Units
  units: {
    vnd: 'đ',
    pieces: 'cái',
    items: 'sản phẩm',
    percentage: '%',
  },
}

export default VI_ADMIN
