// Vietnamese language constants
export const VI = {
  // Common
  common: {
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    success: 'Thành công',
    cancel: 'Hủy',
    save: 'Lưu',
    delete: 'Xóa',
    edit: 'Sửa',
    add: 'Thêm',
    search: 'Tìm kiếm',
    filter: 'Lọc',
    sort: 'Sắp xếp',
    viewAll: 'Xem tất cả',
    backToHome: 'Về trang chủ',
    home: 'Trang chủ',
    products: 'Sản phẩm',
    cart: 'Giỏ hàng',
    orders: 'Đơn hàng',
    profile: 'Tài khoản',
    searchPlaceholder: 'Tìm kiếm sản phẩm...',
  },

  // Navigation
  nav: {
    home: 'Trang chủ',
    products: 'Sản phẩm',
    allProducts: 'Tất cả sản phẩm',
    featured: 'Nổi bật',
    cart: 'Giỏ hàng',
    viewCart: 'Xem giỏ hàng',
    checkout: 'Thanh toán',
    account: 'Tài khoản',
    orders: 'Đơn hàng',
    profile: 'Hồ sơ',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    register: 'Đăng ký',
  },

  // Auth
  auth: {
    welcomeBack: 'Chào mừng trở lại',
    signInToAccount: 'Đăng nhập vào tài khoản của bạn',
    emailAddress: 'Địa chỉ Email',
    password: 'Mật khẩu',
    rememberMe: 'Ghi nhớ đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    signIn: 'Đăng nhập',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    signUp: 'Đăng ký',
    loggingIn: 'Đang đăng nhập...',
    orContinueWith: 'Hoặc tiếp tục với',
    continueWithGoogle: 'Tiếp tục với Google',
    dontHaveAccount: 'Chưa có tài khoản?',
    signUpFree: 'Đăng ký miễn phí',
    createAccount: 'Tạo tài khoản',
    joinToday: 'Tham gia ngay hôm nay và bắt đầu mua sắm',
    fullName: 'Họ và tên',
    phoneNumber: 'Số điện thoại',
    address: 'Địa chỉ',
    agreeToTerms: 'Tôi đồng ý với',
    termsAndConditions: 'Điều khoản và Điều kiện',
    and: 'và',
    privacyPolicy: 'Chính sách Bảo mật',
    createAccountBtn: 'Tạo tài khoản',
    creatingAccount: 'Đang tạo tài khoản...',
    alreadyHaveAccount: 'Đã có tài khoản?',
    signInHere: 'Đăng nhập tại đây',
    pleaseLogin: 'Vui lòng đăng nhập để thêm vào giỏ hàng',
    mustBeAtLeast6Chars: 'Phải có ít nhất 6 ký tự',
  },

  // Products
  products: {
    allProducts: 'Tất cả sản phẩm',
    featuredProducts: 'Sản phẩm nổi bật',
    searchResults: 'Kết quả tìm kiếm',
    searchPlaceholder: 'Tìm kiếm laptop, phụ kiện...',
    noProductsFound: 'Không tìm thấy sản phẩm phù hợp',
    tryAdjustingFilters: 'Thử điều chỉnh bộ lọc hoặc từ khóa tìm kiếm của bạn',
    clearFilters: 'Xóa bộ lọc',
    sortBy: 'Sắp xếp theo',
    priceRange: 'Khoảng giá',
    brand: 'Thương hiệu',
    category: 'Danh mục',
    allBrands: 'Tất cả thương hiệu',
    allCategories: 'Tất cả danh mục',
    featured: 'Nổi bật',
    priceLowToHigh: 'Giá: Thấp đến Cao',
    priceHighToLow: 'Giá: Cao đến Thấp',
    nameAZ: 'Tên: A-Z',
    nameZA: 'Tên: Z-A',
    addToCart: 'Thêm vào giỏ',
    addedToCart: '✓ Đã thêm vào giỏ',
    buyNow: 'Mua ngay',
    specifications: 'Thông số kỹ thuật',
    description: 'Mô tả',
    reviews: 'Đánh giá',
    relatedProducts: 'Sản phẩm liên quan',
    inStock: 'Còn hàng',
    outOfStock: 'Hết hàng',
  },

  // Cart
  cart: {
    title: 'Giỏ hàng của bạn',
    emptyCart: 'Giỏ hàng trống',
    emptyCartMessage: 'Giỏ hàng của bạn đang trống. Hãy thêm một số sản phẩm!',
    continueShopping: 'Tiếp tục mua sắm',
    product: 'Sản phẩm',
    quantity: 'Số lượng',
    price: 'Giá',
    total: 'Tổng cộng',
    subtotal: 'Tạm tính',
    shipping: 'Phí vận chuyển',
    tax: 'Thuế',
    discount: 'Giảm giá',
    grandTotal: 'Tổng thanh toán',
    proceedToCheckout: 'Tiến hành thanh toán',
    remove: 'Xóa',
    update: 'Cập nhật',
  },

  // Checkout
  checkout: {
    title: 'Thanh toán',
    shippingAddress: 'Địa chỉ giao hàng',
    billingInfo: 'Thông tin thanh toán',
    fullName: 'Họ và tên',
    phone: 'Số điện thoại',
    address: 'Địa chỉ',
    city: 'Thành phố',
    district: 'Quận/Huyện',
    ward: 'Phường/Xã',
    billingName: 'Tên người thanh toán',
    billingAddress: 'Địa chỉ thanh toán',
    subtotal: 'Tạm tính',
    shipping: 'Phí vận chuyển',
    discount: 'Giảm giá',
    total: 'Tổng cộng',
    couponCode: 'Mã giảm giá',
    apply: 'Áp dụng',
    confirmPayment: 'Xác nhận thanh toán',
    emptyCart: 'Giỏ hàng trống — vui lòng thêm sản phẩm trước khi thanh toán',
    shippingInformation: 'Thông tin giao hàng',
    paymentMethod: 'Phương thức thanh toán',
    orderSummary: 'Tóm tắt đơn hàng',
    placeOrder: 'Đặt hàng',
    placingOrder: 'Đang đặt hàng...',
    orderSuccess: 'Đặt hàng thành công!',
    orderSuccessMessage: 'Cảm ơn bạn đã đặt hàng. Chúng tôi sẽ xử lý đơn hàng của bạn sớm nhất.',
    viewOrders: 'Xem đơn hàng',
    cashOnDelivery: 'Thanh toán khi nhận hàng',
    creditCard: 'Thẻ tín dụng',
    bankTransfer: 'Chuyển khoản ngân hàng',
  },

  // Orders
  orders: {
    title: 'Đơn hàng của tôi',
    noOrders: 'Chưa có đơn hàng',
    noOrdersMessage: 'Bạn chưa có đơn hàng nào. Hãy bắt đầu mua sắm!',
    orderNumber: 'Mã đơn hàng',
    orderDate: 'Ngày đặt',
    status: 'Trạng thái',
    totalAmount: 'Tổng tiền',
    viewDetails: 'Xem chi tiết',
    orderDetails: 'Chi tiết đơn hàng',
    orderItems: 'Sản phẩm đã đặt',
    shippingAddress: 'Địa chỉ giao hàng',
    paymentStatus: 'Trạng thái thanh toán',
    pending: 'Đang xử lý',
    processing: 'Đang xử lý',
    shipped: 'Đã gửi hàng',
    delivered: 'Đã giao hàng',
    cancelled: 'Đã hủy',
    paid: 'Đã thanh toán',
    unpaid: 'Chưa thanh toán',
  },

  // Profile
  profile: {
    title: 'Hồ sơ của tôi',
    personalInformation: 'Thông tin cá nhân',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    updateProfile: 'Cập nhật hồ sơ',
    updating: 'Đang cập nhật...',
  },

  // Footer
  footer: {
    aboutUs: 'Về chúng tôi',
    aboutDescription: 'GearUp là cửa hàng laptop uy tín, cung cấp các sản phẩm chính hãng với giá tốt nhất.',
    quickLinks: 'Liên kết nhanh',
    categories: 'Danh mục',
    customerService: 'Dịch vụ khách hàng',
    contactUs: 'Liên hệ',
    shippingPolicy: 'Chính sách vận chuyển',
    returnPolicy: 'Chính sách đổi trả',
    warrantyPolicy: 'Chính sách bảo hành',
    faq: 'Câu hỏi thường gặp',
    followUs: 'Theo dõi chúng tôi',
    allRightsReserved: 'Bản quyền thuộc về',
  },

  // Home
  home: {
    heroTitle: 'Khám phá thế giới công nghệ',
    heroSubtitle: 'Laptop chính hãng - Giá tốt nhất - Bảo hành uy tín',
    shopNow: 'Mua ngay',
    exploreCategories: 'Khám phá danh mục',
    categoriesDescription: 'Khám phá các danh mục sản phẩm của chúng tôi',
  },

  // Error messages
  errors: {
    somethingWentWrong: 'Đã có lỗi xảy ra',
    pleaseTryAgain: 'Vui lòng thử lại',
    loginFailed: 'Đăng nhập thất bại',
    registrationFailed: 'Đăng ký thất bại',
    invalidEmailOrPassword: 'Email hoặc mật khẩu không đúng',
    emailAlreadyExists: 'Email đã tồn tại',
    invalidEmail: 'Email không hợp lệ',
    passwordTooShort: 'Mật khẩu quá ngắn',
    passwordsDoNotMatch: 'Mật khẩu không khớp',
    requiredField: 'Trường này là bắt buộc',
    invalidPhone: 'Số điện thoại không hợp lệ',
    uploadFailed: 'Tải lên thất bại',
    updateFailed: 'Cập nhật thất bại',
    deleteFailed: 'Xóa thất bại',
  },

  // Units
  units: {
    vnd: 'đ',
    items: 'sản phẩm',
    piece: 'cái',
  },
}

export default VI
